name: artiluxio
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.2
  tflite_flutter: ^0.9.0
  image_picker: ^0.8.6+3
  flutter_speed_dial: ^6.2.0
  photo_view: ^0.14.0
  path_provider: ^2.0.13
  image: ^4.0.15
  share_plus: 3.0.0 # because of conflicts with tflite

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/example.jpg 
    - assets/style_images/
    - assets/logo.png
    - assets/models/

  fonts:
     - family: Roboto
       fonts:
         - asset: fonts/Roboto-Thin.ttf
         - asset: fonts/Roboto-Light.ttf
         - asset: fonts/Roboto-Regular.ttf
         - asset: fonts/Roboto-Black.ttf